jobs:
  basics:
    runs-on: ubuntu-latest

    steps:
      - name: welcome
        run: echo "welcome to devops"

      - name: Date
        run: date

      - name: git version
        run: git --version
