name: Multi Job Workflow

on: push

jobs:
  greeting:
    runs-on: ubuntu-latest

    steps:
      - name: Welcome
        run: echo "Hello Sai"

  systeminfo:
    runs-on: ubuntu-latest

    steps:
      - name: Show Date
        run: date
